# Generated by Django 2.2.2 on 2019-06-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pup_date',
            new_name='pub_date',
        ),
    ]
